AWSTemplateFormatVersion: '2010-09-09'
Description: EKS Cluster Stack

Parameters:
  pClusterName:
    Type: String
    Default: cluster-eks-dev

Resources:
  rEKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${pClusterName}-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  rEKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref pClusterName
      Version: "1.29"
      RoleArn: !GetAtt rEKSClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds:
          - !ImportValue rPublicSubnet1
          - !ImportValue rPublicSubnet2
        EndpointPublicAccess: true
        EndpointPrivateAccess: false
        #Habilitamos logs de cloudwatchs acerca el Cluster-EKS
    Logging:
      ClusterLogging:
        EnabledTypes:
          - Type: api
          - Type: audit
          - Type: authenticator
          - Type: controllerManager
          - Type: scheduler

Outputs:
  oClusterName:
    Description: name cluster EKS
    Value: !Ref rEKSCluster

  oClusterArn:
    Description: ARN cluster
    Value: !GetAtt rEKSCluster.Arn
