AWSTemplateFormatVersion: '2010-09-09'
Description: EKS Node Group Stack

Parameters:
  pClusterName:
    Type: String
    Default: cluster-eks-dev

Resources:
  rNodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${pClusterName}-node-rol"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

  rNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref pClusterName
      NodegroupName: !Sub "${pClusterName}-nodegroup-eks"
      NodeRole: !GetAtt rNodeInstanceRole.Arn
      Subnets:
        - !ImportValue rPublicSubnet1
        - !ImportValue rPublicSubnet2
      ScalingConfig:
        DesiredSize: 1
        MinSize: 1
        MaxSize: 1
      InstanceTypes:
        - t3.medium
      AmiType: AL2_x86_64
      CapacityType: ON_DEMAND
