AWSTemplateFormatVersion: '2010-09-09'
Description: RDS PostgreSQL for Roles App

Parameters:

  VpcId:
    Type: String

  PrivateSubnet1:
    Type: String

  PrivateSubnet2:
    Type: String

  DBUsername:
    Type: String
    Default: postgres

  DBPassword:
    Type: String
    NoEcho: true

Resources:

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow PostgreSQL access
      VpcId: !Ref VpcId

  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2

  PostgresDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: roles-db
      Engine: postgres
      EngineVersion: "15.4"
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref RDSSubnetGroup
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      PubliclyAccessible: false
      MultiAZ: false
      StorageType: gp2
      BackupRetentionPeriod: 0
      DeletionProtection: false

Outputs:

  DBEndpoint:
    Value: !GetAtt PostgresDB.Endpoint.Address

  DBPort:
    Value: !GetAtt PostgresDB.Endpoint.Port