AWSTemplateFormatVersion: '2010-09-09'
Description: RDS PostgreSQL for Roles Application

Parameters:
  pDBUsername:
    Type: String

  pDBPassword:
    Type: String
    NoEcho: true

Resources:
  rDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow PostgreSQL access
      VpcId: vpc-08ddaa02b7da006ed
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 181.235.17.205/32
      Tags:
        - Key: Name
          Value: roles-dev-rds-sg

  rDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets for RDS
      SubnetIds:
        - subnet-02622c5827c459721 #subnetspublica1
        - subnet-02280c2114b8f782e #subnetspublica2
      Tags:
        - Key: Name
          Value: roles-dev-db-subnet-group

  rPostgreSQLDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: roles-dev-postgres
      Engine: postgres
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      MasterUsername: !Ref pDBUsername
      MasterUserPassword: !Ref pDBPassword
      DBSubnetGroupName: !Ref rDBSubnetGroup
      VPCSecurityGroups:
        - !Ref rDBSecurityGroup
      PubliclyAccessible: true
      MultiAZ: false
      StorageType: gp2
      BackupRetentionPeriod: 0
      Tags:
        - Key: Name
          Value: roles-dev-postgres
