AWSTemplateFormatVersion: '2010-09-09'
Description: VPC for Roles Service (ECS + RDS)

Resources:
  rRolesVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: roles-vpc

  rInternetGateway:
    Type: AWS::EC2::InternetGateway

  rAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref rRolesVPC
      InternetGatewayId: !Ref rInternetGateway

  rPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref rRolesVPC
      Tags:
        - Key: Name
          Value: roles-public-route


  rDefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: rAttachGateway
    Properties:
      RouteTableId: !Ref rPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref rInternetGateway

  rPublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref rPublicSubnet1
      RouteTableId: !Ref rPublicRouteTable

  rPublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref rPublicSubnet2
      RouteTableId: !Ref rPublicRouteTable

  rPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref rRolesVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: us-east-1a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet1

  rPublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref rRolesVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: us-east-1b
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet2

  rPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref rRolesVPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: us-east-1a
      Tags:
        - Key: Name
          Value: PrivateSubnet1

  rPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref rRolesVPC
      CidrBlock: 10.0.4.0/24
      AvailabilityZone: us-east-1b
      Tags:
        - Key: Name
          Value: PrivateSubnet2

Outputs:

  oVpcId:
    Value: !Ref rRolesVPC

  oPublicSubnet1:
    Value: !Ref rPublicSubnet1

  oPublicSubnet2:
    Value: !Ref rPublicSubnet2

  oPrivateSubnet1:
    Value: !Ref rPrivateSubnet1

  oPrivateSubnet2:
    Value: !Ref rPrivateSubnet2