name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy IaC"
        required: true
        default: "dev"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::279981432284:role/GitHub_Cloud_IaC_Rol
          aws-region: us-east-1

      - name: Deploy VPC-Stack
        if: ${{ github.event.inputs.environment == 'true' }}
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/vpc.yaml \
            --stack-name roles-vpc-dev-stack \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Deploy RDS-Stack
        if: ${{ github.event.inputs.environment == 'true' }}
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/rds.yaml \
            --stack-name roles-rds-dev-stack \
            --parameter-overrides \
            pDBUsername=${{ vars.DB_USERNAME }} \
            pDBPassword=${{ secrets.DB_PASSWORD }} \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Deploy Cluster-EKS-Stack
        if: ${{ github.event.inputs.environment == 'true' }}
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/EKS/cluster.yaml \
            --stack-name roles-cluster-eks-stack-dev \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Deploy nodegroup-EKS-Stack
        if: ${{ github.event.inputs.environment == 'true' }}
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/EKS/nodegroup.yaml \
            --stack-name roles-nodegroup-eks-stack-dev \
            --capabilities CAPABILITY_NAMED_IAM
